---
driver:
  name: docker
  use_sudo: false

provisioner:
  hosts: test-kitchen
  name: ansible_playbook
  require_chef_for_busser: false
  ansible_verbosity: 2
  ansible_verbose: true
  ansible_extra_flags: '--skip-tags=create_droplet,add_ssh_key'
  idempotency_test: true

platforms:
  - name: ubuntu-16.04
    driver_config:
      image: williamyeh/ansible:ubuntu16.04-onbuild
      platform: ubuntu
  - name: ubuntu-14.04
    driver_config:
      image: williamyeh/ansible:ubuntu14.04-onbuild
      platform: ubuntu
  - name: centos-7.0
    driver_config:
      image: williamyeh/ansible:centos7-onbuild
      platform: centos
  - name: debian-9
    driver_config:
      image: williamyeh/ansible:debian9-onbuild
      platform: debian
  - name: debian-8
    driver_config:
      image: williamyeh/ansible:debian8-onbuild
      platform: debian

verifier:
  name: serverspec

suites:
  - name: droplet
    driver:
      provision_command: 
        - export LC_ALL=C
    verifier:
      default_pattern: true
      bundler_path: '/usr/local/bin'
      rspec_path: '/usr/local/bin'