---
sudo: required
services:
  - docker

language: python
python: "2.7"

env:
  - ANSIBLE_VERSION: latest
  - ANSIBLE_VERSION: 2.4.0.0
  - ANSIBLE_VERSION: 2.3.0.0
  - ANSIBLE_VERSION: 2.2.0.0
  - ANSIBLE_VERSION: 2.1.0.0

cache:
  pip: true
  directories:
    - $HOME/.rvm/gems

before_install:
  - sudo apt-get update -qq
  - sleep 5
  - sudo apt-get install -qq python-apt python-pycurl
  - gem install bundler

install:
  - bundle install
  - if [ "$ANSIBLE_VERSION" = "latest" ]; then pip install ansible; else pip install ansible==$ANSIBLE_VERSION; fi

script:
  - export ANSIBLE_CONFIG="test/ansible.cfg"
  - ansible --version
  - docker version
  - export LC_ALL=C
  - bundle show
  - bundle exec kitchen test -c

notifications:
  email:
    on_success: never
  webhooks: https://galaxy.ansible.com/api/v1/notifications/