---
- name: Update apt packages
  apt:
    update_cache: yes
    cache_valid_time: 3600

- name: Install Python 2.x
  raw: which python || sudo apt-get update && sudo apt-get install -qq -y python-simplejson
  register: python_check
  changed_when: not python_check.stdout | search('/usr/bin/python')

- name: Install pip
  apt:
    name: python-pip
    state: present
    update_cache: yes